#!/usr/bin/env bash

function _make_profile {
  local shome="${_make_home:="$(cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"}"
  PATH="$shome/bin:$shome/exec:$PATH"
  
  export GMSL="$_make_home"
}

_make_profile
