#!/usr/bin/env bash

function version {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  local ver_gmsl="$GMSL_VERSION"
  jq -n --arg gmsl "$ver_gmsl" '{gmsl: $gmsl}'
}

version "$@"
