#!/usr/bin/env bash

function version {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  local ver_make="0.0.1"
  jq -n --arg make "$ver_make" '{make: $make}'
}

version "$@"
